version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: transaction-db
      POSTGRES_USER: market
      POSTGRES_PASSWORD: fixme
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U market"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: